dist: trusty
language: clojure
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
lein: 2.6.1
script:
  - lein with-profile 1.6 test
  - lein with-profile 1.7 test
  - lein with-profile 1.9 test
  - lein test
